import {useEffect,useState} from "react";
import {Link,useLocation} from "react-router-dom";
import {CHAIN_ID,CONTRACT_ADDRESS} from "@/lib/genlayer/config";
import {useWallet} from "./wallet-provider";
const short=(v?:string)=>v?`${v.slice(0,6)}…${v.slice(-4)}`:"";
const THEME_KEY="lorechain.theme";
type Theme="light"|"dark";
const readTheme=():Theme=>{try{const stored=window.localStorage.getItem(THEME_KEY);if(stored==="dark"||stored==="light")return stored;}catch{/* storage may be unavailable */}return document.documentElement.dataset.theme==="dark"?"dark":"light";};
export function AppShell({children}:{children:React.ReactNode}){const path=useLocation().pathname;const w=useWallet();const [theme,setTheme]=useState<Theme>(readTheme);useEffect(()=>{document.documentElement.dataset.theme=theme;try{window.localStorage.setItem(THEME_KEY,theme);}catch{/* storage may be unavailable */}},[theme]);return <div className="site-shell"><header className="masthead"><div className="masthead-brand"><Link to="/" className="wordmark"><span className="wordmark-mark">LC</span><span><strong>LoreChain</strong><small>consensus story bible</small></span></Link><div className="live-stamp" data-live={CONTRACT_ADDRESS?"yes":"no"}><span className="live-dot"/>{CONTRACT_ADDRESS?"StudioNet live":"Contract not configured"}</div><button className="theme-toggle" type="button" onClick={()=>setTheme(t=>t==="dark"?"light":"dark")} aria-label={`Switch to ${theme==="dark"?"light":"dark"} theme`}><span className="theme-swatch" aria-hidden="true"/>{theme==="dark"?"Dark":"Light"}</button></div><nav className="masthead-nav"><Link to="/" data-active={path==="/"}>Home</Link><Link to="/desk" data-active={path==="/desk"}>World desk</Link><Link to="/search" data-active={path==="/search"}>Semantic recall</Link></nav><div className="wallet-utility"><span className="network-caption">{w.hydrating?"Checking wallet…":`${w.networkName}${w.network==="correct"?` · ${CHAIN_ID}`:""}`}</span>{w.hydrating?null:w.address&&w.signature?<><span className="wallet-address">{short(w.address)}</span>{w.network==="wrong"&&<button className="text-action" onClick={w.switchNetwork}>Switch network</button>}<button className="text-action" onClick={w.disconnect}>Disconnect</button></>:<button className="connect-button" onClick={w.connect} disabled={w.connecting}>{w.connecting?"Signing in…":w.hasInjected?"Sign in with wallet":"Wallet unavailable"}</button>}</div></header>{w.error&&<div className="wallet-alert" role="alert">{w.error}</div>}<main>{children}</main><footer className="site-footer"><span>LoreChain · lorechain state lives on GenLayer</span><span>StudioNet · chain 61999</span></footer></div>}
