export type NetworkVerdict = "correct" | "wrong" | "unknown";
export type WalletState = { mode:"none"|"injected"; address?:`0x${string}`; chainId?:number; error?:string; signature?:string };
export const DISCONNECTED:WalletState={mode:"none"};
export const MANUAL_DISCONNECT_KEY="lorechain.wallet.manualDisconnect";
export const SIGNED_IN_KEY="lorechain.wallet.signedIn";
export function parseChainId(value:unknown):number|undefined { if(typeof value==="number"&&Number.isFinite(value))return value; if(typeof value!=="string")return undefined; const n=value.startsWith("0x")?Number.parseInt(value.slice(2),16):Number.parseInt(value,10); return Number.isFinite(n)?n:undefined; }
export const chainIdHex=(id:number)=>`0x${id.toString(16)}`;
export function storedSignature(address?:string,chainId?:number):{signature:string}|undefined { if(typeof window==="undefined"||!address)return undefined; try{const raw=window.localStorage.getItem(SIGNED_IN_KEY);if(!raw)return undefined;const parsed=JSON.parse(raw)as{address?:unknown;chainId?:unknown;signature?:unknown};if(parsed.address===address&&parsed.chainId===(chainId ?? null)&&typeof parsed.signature==="string")return {signature:parsed.signature};return undefined;}catch{return undefined;} }
export function storeSignature(address:`0x${string}`,chainId:number|undefined,signature:string){ try{window.localStorage.setItem(SIGNED_IN_KEY,JSON.stringify({address,chainId:chainId ?? null,signature,at:Date.now()}));return true as const;}catch{return false as const;} }
export function clearSignature(){ try{window.localStorage.removeItem(SIGNED_IN_KEY);return true as const;}catch{return false as const;} }
export function networkVerdict(wallet:WalletState,expected:number):NetworkVerdict { if(wallet.mode!=="injected"||wallet.chainId===undefined)return "unknown"; return wallet.chainId===expected?"correct":"wrong"; }
export function networkLabel(verdict:NetworkVerdict,chainName:string,actual?:number){ if(verdict==="correct")return chainName; if(verdict==="wrong")return `Chain ${actual??"unknown"}`; return "Not connected"; }
export function writeGate(wallet:WalletState,expected:number,chainName:string){ if(wallet.mode!=="injected"||!wallet.address)return {canWrite:false,message:"Sign in with an injected wallet to write."}; if(!wallet.signature)return {canWrite:false,message:"Sign in with your wallet to write."}; if(wallet.chainId!==expected)return {canWrite:false,message:`Switch your wallet to ${chainName} before writing.`}; return {canWrite:true as const,message:undefined}; }
export function nextWalletState(wallet:WalletState,event:{type:"connected";address:`0x${string}`;chainId?:number;signature?:string}|{type:"accounts-changed";accounts:unknown}|{type:"chain-changed";chainId:unknown}|{type:"provider-disconnected";message?:string}|{type:"connection-refused";message:string}|{type:"forget"}):WalletState { if(event.type==="connected")return {mode:"injected",address:event.address,chainId:event.chainId,signature:event.signature}; if(event.type==="forget")return DISCONNECTED; if(event.type==="connection-refused")return {...wallet,error:event.message}; if(event.type==="provider-disconnected")return {mode:"none",error:event.message}; if(event.type==="chain-changed"){const nextChainId=parseChainId(event.chainId);return {...wallet,chainId:nextChainId,error:undefined,signature:wallet.chainId===nextChainId?wallet.signature:undefined};} if(event.type==="accounts-changed"){const accounts=Array.isArray(event.accounts)?event.accounts:[];const first=accounts[0];if(typeof first!=="string"||!first.startsWith("0x"))return DISCONNECTED;return {...wallet,mode:"injected",address:first as `0x${string}`,error:undefined,signature:wallet.address===first?wallet.signature:undefined}} return wallet; }
export function applyProviderEvent(wallet:WalletState,event:Parameters<typeof nextWalletState>[1],manualDisconnect:boolean):WalletState { if(manualDisconnect&&(event.type==="accounts-changed"||event.type==="chain-changed"))return DISCONNECTED; return nextWalletState(wallet,event); }
export function hydrateWalletState(accounts:unknown,chainId:unknown,manualDisconnect:boolean,signature?:string):WalletState { if(manualDisconnect||!Array.isArray(accounts)||typeof accounts[0]!=="string"||!accounts[0].startsWith("0x"))return DISCONNECTED; return nextWalletState(DISCONNECTED,{type:"connected",address:accounts[0] as `0x${string}`,chainId:parseChainId(chainId),signature}); }
